
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid1', now(), 'enterpriseurl1', 'objectid1', 'orgid1', 'partnerurl1','sessionid1');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid2', now(), 'enterpriseurl2', 'objectid2', 'orgid2', 'partnerurl2','sessionid2');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid3', now(), 'enterpriseurl3', 'objectid3', 'orgid3', 'partnerurl3','sessionid3');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid4', now(), 'enterpriseurl4', 'objectid4', 'orgid4', 'partnerurl4','sessionid4');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid5', now(), 'enterpriseurl5', 'objectid5', 'orgid5', 'partnerurl5','sessionid5');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid6', now(), 'enterpriseurl6', 'objectid6', 'orgid6', 'partnerurl6','sessionid6');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid7', now(), 'enterpriseurl7', 'objectid7', 'orgid7', 'partnerurl7','sessionid7');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid8', now(), 'enterpriseurl8', 'objectid8', 'orgid8', 'partnerurl8','sessionid8');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid9', now(), 'enterpriseurl9', 'objectid9', 'orgid9', 'partnerurl9','sessionid9');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid10', now(), 'enterpriseurl10', 'objectid10', 'orgid10', 'partnerurl10','sessionid10');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid11', now(), 'enterpriseurl11', 'objectid11', 'orgid11', 'partnerurl11','sessionid11');
insert into receivedmessage (id, actionid, datereceived, enterpriseurl, objectid,orgid, partnerurl, sessionid) values (nextval('hibernate_sequence') , 'actionid12', now(), 'enterpriseurl12', 'objectid12', 'orgid12', 'partnerurl12','sessionid12');